
import type { Student, Subject, Fee, User, FormDocument, Staff, StaffRole } from './types';

export const STUDENTS: Student[] = [
  {
    id: 'SID-1001',
    name: 'Liam Johnson',
    age: 4,
    dob: '2020-05-23',
    guardian1: { firstName: 'Sarah', lastName: 'Johnson', relationship: 'Mother', contact: 'liam.johnson.parent@example.com', phone: '876-555-0101' },
    avatarUrl: 'https://picsum.photos/seed/101/100/100',
    imageHint: 'child smiling',
    afterCare: true,
    nursery: false,
    status: 'enrolled',
    address: '123 Maple St',
    city: 'Kingston',
    state: 'St. Andrew',
    emergencyContactName: 'Robert Johnson',
    emergencyContactPhone: '876-555-0102',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1002',
    name: 'Olivia Williams',
    age: 5,
    dob: '2019-08-15',
    guardian1: { firstName: 'David', lastName: 'Williams', relationship: 'Father', contact: 'olivia.williams.parent@example.com', phone: '876-555-0103' },
    avatarUrl: 'https://picsum.photos/seed/102/100/100',
    imageHint: 'girl laughing',
    afterCare: false,
    nursery: true,
    status: 'enrolled',
    address: '456 Oak Ave',
    city: 'Montego Bay',
    state: 'St. James',
    emergencyContactName: 'Mary Williams',
    emergencyContactPhone: '876-555-0104',
    medicalConditions: 'Peanut allergy',
  },
  {
    id: 'SID-1003',
    name: 'Noah Brown',
    age: 4,
    dob: '2020-01-30',
    guardian1: { firstName: 'Jessica', lastName: 'Brown', relationship: 'Mother', contact: 'noah.brown.parent@example.com', phone: '876-555-0105' },
    avatarUrl: 'https://picsum.photos/seed/103/100/100',
    imageHint: 'boy playing',
    afterCare: true,
    nursery: true,
    status: 'enrolled',
    address: '789 Pine Ln',
    city: 'Ocho Rios',
    state: 'St. Ann',
    emergencyContactName: 'James Brown',
    emergencyContactPhone: '876-555-0106',
    medicalConditions: 'Asthma',
  },
  {
    id: 'SID-1004',
    name: 'Emma Jones',
    age: 3,
    dob: '2021-11-10',
    guardian1: { firstName: 'Michael', lastName: 'Jones', relationship: 'Father', contact: 'emma.jones.parent@example.com', phone: '876-555-0107' },
    avatarUrl: 'https://picsum.photos/seed/104/100/100',
    imageHint: 'toddler girl',
    afterCare: false,
    nursery: true,
    status: 'pending',
    address: '101 Elm Ct',
    city: 'Spanish Town',
    state: 'St. Catherine',
    emergencyContactName: 'Linda Jones',
    emergencyContactPhone: '876-555-0108',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1005',
    name: 'Lucas Garcia',
    age: 5,
    dob: '2019-03-25',
    guardian1: { firstName: 'Maria', lastName: 'Garcia', relationship: 'Mother', contact: 'lucas.garcia.parent@example.com', phone: '876-555-0109' },
    avatarUrl: 'https://picsum.photos/seed/105/100/100',
    imageHint: 'child portrait',
    afterCare: true,
    nursery: false,
    status: 'enrolled',
    address: '212 Birch Rd',
    city: 'Mandeville',
    state: 'Manchester',
    emergencyContactName: 'Carlos Garcia',
    emergencyContactPhone: '876-555-0110',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1006',
    name: 'Ava Miller',
    age: 4,
    dob: '2020-09-05',
    guardian1: { firstName: 'Chris', lastName: 'Miller', relationship: 'Father', contact: 'ava.miller.parent@example.com', phone: '876-555-0111' },
    avatarUrl: 'https://picsum.photos/seed/106/100/100',
    imageHint: 'child painting',
    afterCare: false,
    nursery: false,
    status: 'enrolled',
    address: '333 Cedar Dr',
    city: 'Negril',
    state: 'Westmoreland',
    emergencyContactName: 'Patricia Miller',
    emergencyContactPhone: '876-555-0112',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1007',
    name: 'Mason Rodriguez',
    age: 5,
    dob: '2019-07-19',
    guardian1: { firstName: 'Jennifer', lastName: 'Rodriguez', relationship: 'Mother', contact: 'mason.rodriguez.parent@example.com', phone: '876-555-0113' },
    avatarUrl: 'https://picsum.photos/seed/107/100/100',
    imageHint: 'boy running',
    afterCare: true,
    nursery: true,
    status: 'enrolled',
    address: '444 Spruce Way',
    city: 'Port Antonio',
    state: 'Portland',
    emergencyContactName: 'Jose Rodriguez',
    emergencyContactPhone: '876-555-0114',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1008',
    name: 'Sophia Martinez',
    age: 3,
    dob: '2021-02-12',
    guardian1: { firstName: 'Robert', lastName: 'Martinez', relationship: 'Father', contact: 'sophia.martinez.parent@example.com', phone: '876-555-0115' },
    avatarUrl: 'https/picsum.photos/seed/108/100/100',
    imageHint: 'girl with book',
    afterCare: false,
    nursery: true,
    status: 'enrolled',
    address: '555 Willow Ave',
    city: 'May Pen',
    state: 'Clarendon',
    emergencyContactName: 'Maria Martinez',
    emergencyContactPhone: '876-555-0116',
    medicalConditions: 'Lactose intolerant',
  },
  {
    id: 'SID-1009',
    name: 'Ethan Hernandez',
    age: 4,
    dob: '2020-04-01',
    guardian1: { firstName: 'Lisa', lastName: 'Hernandez', relationship: 'Mother', contact: 'ethan.hernandez.parent@example.com', phone: '876-555-0117' },
    avatarUrl: 'https/picsum.photos/seed/109/100/100',
    imageHint: 'child on swing',
    afterCare: true,
    nursery: false,
    status: 'pending',
    address: '666 Redwood Cir',
    city: 'Falmouth',
    state: 'Trelawny',
    emergencyContactName: 'Juan Hernandez',
    emergencyContactPhone: '876-555-0118',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1010',
    name: 'Isabella Lopez',
    age: 5,
    dob: '2019-10-08',
    guardian1: { firstName: 'Daniel', lastName: 'Lopez', relationship: 'Father', contact: 'isabella.lopez.parent@example.com', phone: '876-555-0119' },
    avatarUrl: 'https://picsum.photos/seed/110/100/100',
    imageHint: 'girl smiling',
    afterCare: false,
    nursery: true,
    status: 'enrolled',
    address: '777 Sequoia Blvd',
    city: 'Black River',
    state: 'St. Elizabeth',
    emergencyContactName: 'Ana Lopez',
    emergencyContactPhone: '876-555-0120',
    medicalConditions: 'None',
  }
];

export const ARCHIVED_STUDENTS: Student[] = [
    {
        id: 'SID-9001',
        name: 'Michael Clark',
        age: 6,
        dob: '2018-03-15',
        guardian1: { firstName: 'Linda', lastName: 'Clark', relationship: 'Mother', contact: 'linda.clark@example.com', phone: '876-555-0201' },
        avatarUrl: 'https://picsum.photos/seed/901/100/100',
        imageHint: 'boy with backpack',
        status: 'graduated',
        graduationDate: '2023-06-15T12:00:00.000Z',
    },
    {
        id: 'SID-9002',
        name: 'Emily Lewis',
        age: 6,
        dob: '2018-05-20',
        guardian1: { firstName: 'Paul', lastName: 'Lewis', relationship: 'Father', contact: 'paul.lewis@example.com', phone: '876-555-0202' },
        avatarUrl: 'https://picsum.photos/seed/902/100/100',
        imageHint: 'girl in cap and gown',
        status: 'graduated',
        graduationDate: '2023-06-15T12:00:00.000Z',
    },
];

export const SUBJECTS: Subject[] = [
  { id: 'math', name: 'Math' },
  { id: 'science', name: 'Science' },
  { id: 'reading', name: 'Reading' },
  { id: 'art', name: 'Art' },
  { id: 'music', name: 'Music' },
];

export const GRADES: Grade[] = [];

export const ATTENDANCE: Attendance[] = [];

export const FEES: Fee[] = [
  { id: 'fee-1001', studentId: 'SID-1001', amount: 3000, amountPaid: 3000, status: 'Paid', plan: 'Full Payment' },
  { id: 'fee-1002', studentId: 'SID-1002', amount: 2500, amountPaid: 2500, status: 'Paid', plan: 'Two Installments' },
  { id: 'fee-1003', studentId: 'SID-1003', amount: 3000, amountPaid: 1500, status: 'Pending', plan: 'Two Installments' },
  { id: 'fee-1004', studentId: 'SID-1004', amount: 2500, amountPaid: 0, status: 'Pending', plan: 'Monthly Plan' },
  { id: 'fee-1005', studentId: 'SID-1005', amount: 3000, amountPaid: 3000, status: 'Paid', plan: 'Full Payment' },
  { id: 'fee-1006', studentId: 'SID-1006', amount: 2500, amountPaid: 2000, status: 'Pending', plan: 'Monthly Plan' },
  { id: 'fee-1007', studentId: 'SID-1007', amount: 3000, amountPaid: 0, status: 'Overdue', plan: 'Full Payment' },
  { id: 'fee-1008', studentId: 'SID-1008', amount: 2500, amountPaid: 2500, status: 'Paid', plan: 'Full Payment' },
  { id: 'fee-1009', studentId: 'SID-1009', amount: 3000, amountPaid: 500, status: 'Pending', plan: 'Monthly Plan' },
  { id: 'fee-1010', studentId: 'SID-1010', amount: 2500, amountPaid: 1250, status: 'Pending', plan: 'Two Installments' },
];

export const USERS: User[] = [
    {
      id: 'user-1',
      username: 'Admin',
      email: 'admin@example.com',
      role: 'Admin',
      password: 'admin',
      avatarUrl: 'https://picsum.photos/seed/admin/100/100',
      imageHint: 'person avatar'
    },
    {
        id: 'user-2',
        username: 'Teacher',
        email: 'teacher@example.com',
        role: 'Teacher',
        password: 'teacher',
        avatarUrl: 'https://picsum.photos/seed/teacher/100/100',
        imageHint: 'person avatar'
    }
];

export const PERMISSIONS: {id: string, label: string}[] = [
    { id: '/dashboard/preschool', label: 'Preschool Dashboard' },
    { id: '/dashboard/student-management', label: 'Student Management' },
    { id: '/dashboard/attendance', label: 'Attendance' },
    { id: '/dashboard/grades', label: 'Grades' },
    { id: '/dashboard/forms', label: 'Forms' },
    { id: '/dashboard/reports', label: 'Reports' },
    { id: '/dashboard/graduation', label: 'Graduation' },
    { id: '/dashboard/after-care', label: 'After-Care' },
    { id: '/dashboard/nursery', label: 'Nursery' },
    { id: '/dashboard/manage-users', label: 'Manage Users'},
    { id: '/dashboard/staff', label: 'Staff Management' },
];

export const DEFAULT_TEACHER_PERMISSIONS: string[] = ['/dashboard/preschool', '/dashboard/attendance', '/dashboard/grades'];

export const FORMS: FormDocument[] = [
    {
      id: 'f1',
      title: 'New Student Application',
      description: 'Standard application form for all new student registrations.',
      icon: 'FileText',
    },
    {
      id: 'f2',
      title: 'Medical & Consent Form',
      description: 'Emergency contacts and medical consent for treatment.',
      icon: 'HeartPulse',
    },
];

export const STAFF: Staff[] = [
    {
      id: 'staff-1',
      name: 'Eleanor Vance',
      role: 'Preschool Attendant',
      avatarUrl: 'https://i.pravatar.cc/150?u=eleanor',
      imageHint: 'woman smiling'
    },
    {
      id: 'staff-2',
      name: 'Marcus Holloway',
      role: 'Aftercare Attendant',
      avatarUrl: 'https://i.pravatar.cc/150?u=marcus',
      imageHint: 'man with glasses'
    },
    {
      id: 'staff-3',
      name: 'Clara Oswald',
      role: 'Nursery Attendant',
      avatarUrl: 'https://i.pravatar.cc/150?u=clara',
      imageHint: 'woman with dark hair'
    }
];


export const JAMAICAN_PARISHES = [
    { value: 'St. Andrew', label: 'St. Andrew' },
    { value: 'St. Catherine', label: 'St. Catherine' },
    { value: 'Clarendon', label: 'Clarendon' },
    { value: 'Manchester', label: 'Manchester' },
    { value: 'St. Elizabeth', label: 'St. Elizabeth' },
    { value: 'Westmoreland', label: 'Westmoreland' },
    { value: 'Hanover', label: 'Hanover' },
    { value: 'St. James', label: 'St. James' },
    { value: 'Trelawny', label: 'Trelawny' },
    { value: 'St. Ann', label: 'St. Ann' },
    { value: 'St. Mary', label: 'St. Mary' },
    { value: 'Portland', label: 'Portland' },
    { value: 'St. Thomas', label: 'St. Thomas' },
    { value: 'Kingston', label: 'Kingston' },
];
