
import type { Student, Subject, Grade, Attendance, Fee, User } from './types';

export const STUDENTS: Student[] = [
  {
    id: 'SID-1001',
    name: 'Liam Johnson',
    age: 4,
    dob: '2020-05-23',
    parentContact: 'liam.johnson.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/101/100/100',
    imageHint: 'child smiling',
    afterCare: true,
    status: 'enrolled',
    parentFirstName: 'Sarah',
    parentLastName: 'Johnson',
    parentPhone: '555-0101',
    address: '123 Maple St',
    city: 'Sunnydale',
    state: 'CA',
    emergencyContactName: 'Robert Johnson',
    emergencyContactPhone: '555-0102',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1002',
    name: 'Olivia Williams',
    age: 5,
    dob: '2019-08-15',
    parentContact: 'olivia.williams.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/102/100/100',
    imageHint: 'girl laughing',
    afterCare: false,
    status: 'enrolled',
    parentFirstName: 'David',
    parentLastName: 'Williams',
    parentPhone: '555-0103',
    address: '456 Oak Ave',
    city: 'Rivertown',
    state: 'TX',
    emergencyContactName: 'Mary Williams',
    emergencyContactPhone: '555-0104',
    medicalConditions: 'Peanut allergy',
  },
  {
    id: 'SID-1003',
    name: 'Noah Brown',
    age: 4,
    dob: '2020-01-30',
    parentContact: 'noah.brown.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/103/100/100',
    imageHint: 'boy playing',
    afterCare: true,
    status: 'enrolled',
    parentFirstName: 'Jessica',
    parentLastName: 'Brown',
    parentPhone: '555-0105',
    address: '789 Pine Ln',
    city: 'Hill Valley',
    state: 'FL',
    emergencyContactName: 'James Brown',
    emergencyContactPhone: '555-0106',
    medicalConditions: 'Asthma',
  },
  {
    id: 'SID-1004',
    name: 'Emma Jones',
    age: 3,
    dob: '2021-11-10',
    parentContact: 'emma.jones.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/104/100/100',
    imageHint: 'toddler girl',
    afterCare: false,
    status: 'pending',
    parentFirstName: 'Michael',
    parentLastName: 'Jones',
    parentPhone: '555-0107',
    address: '101 Elm Ct',
    city: 'Springfield',
    state: 'IL',
    emergencyContactName: 'Linda Jones',
    emergencyContactPhone: '555-0108',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1005',
    name: 'Lucas Garcia',
    age: 5,
    dob: '2019-03-25',
    parentContact: 'lucas.garcia.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/105/100/100',
    imageHint: 'child portrait',
    afterCare: true,
    status: 'enrolled',
    parentFirstName: 'Maria',
    parentLastName: 'Garcia',
    parentPhone: '555-0109',
    address: '212 Birch Rd',
    city: 'Greenville',
    state: 'SC',
    emergencyContactName: 'Carlos Garcia',
    emergencyContactPhone: '555-0110',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1006',
    name: 'Ava Miller',
    age: 4,
    dob: '2020-09-05',
    parentContact: 'ava.miller.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/106/100/100',
    imageHint: 'child painting',
    afterCare: false,
    status: 'enrolled',
    parentFirstName: 'Chris',
    parentLastName: 'Miller',
    parentPhone: '555-0111',
    address: '333 Cedar Dr',
    city: 'Lakeside',
    state: 'WA',
    emergencyContactName: 'Patricia Miller',
    emergencyContactPhone: '555-0112',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1007',
    name: 'Mason Rodriguez',
    age: 5,
    dob: '2019-07-19',
    parentContact: 'mason.rodriguez.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/107/100/100',
    imageHint: 'boy running',
    afterCare: true,
    status: 'enrolled',
    parentFirstName: 'Jennifer',
    parentLastName: 'Rodriguez',
    parentPhone: '555-0113',
    address: '444 Spruce Way',
    city: 'Mountainview',
    state: 'CO',
    emergencyContactName: 'Jose Rodriguez',
    emergencyContactPhone: '555-0114',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1008',
    name: 'Sophia Martinez',
    age: 3,
    dob: '2021-02-12',
    parentContact: 'sophia.martinez.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/108/100/100',
    imageHint: 'girl with book',
    afterCare: false,
    status: 'enrolled',
    parentFirstName: 'Robert',
    parentLastName: 'Martinez',
    parentPhone: '555-0115',
    address: '555 Willow Ave',
    city: 'Oceanside',
    state: 'CA',
    emergencyContactName: 'Maria Martinez',
    emergencyContactPhone: '555-0116',
    medicalConditions: 'Lactose intolerant',
  },
  {
    id: 'SID-1009',
    name: 'Ethan Hernandez',
    age: 4,
    dob: '2020-04-01',
    parentContact: 'ethan.hernandez.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/109/100/100',
    imageHint: 'child on swing',
    afterCare: true,
    status: 'pending',
    parentFirstName: 'Lisa',
    parentLastName: 'Hernandez',
    parentPhone: '555-0117',
    address: '666 Redwood Cir',
    city: 'Forest Hills',
    state: 'OR',
    emergencyContactName: 'Juan Hernandez',
    emergencyContactPhone: '555-0118',
    medicalConditions: 'None',
  },
  {
    id: 'SID-1010',
    name: 'Isabella Lopez',
    age: 5,
    dob: '2019-10-08',
    parentContact: 'isabella.lopez.parent@example.com',
    avatarUrl: 'https://picsum.photos/seed/110/100/100',
    imageHint: 'girl smiling',
    afterCare: false,
    status: 'enrolled',
    parentFirstName: 'Daniel',
    parentLastName: 'Lopez',
    parentPhone: '555-0119',
    address: '777 Sequoia Blvd',
    city: 'Bayview',
    state: 'FL',
    emergencyContactName: 'Ana Lopez',
    emergencyContactPhone: '555-0120',
    medicalConditions: 'None',
  }
];

export const SUBJECTS: Subject[] = [
  { id: 'math', name: 'Math' },
  { id: 'science', name: 'Science' },
  { id: 'reading', name: 'Reading' },
  { id: 'art', name: 'Art' },
  { id: 'music', name: 'Music' },
];

export const GRADES: Grade[] = [];

export const ATTENDANCE: Attendance[] = [];

export const FEES: Fee[] = [
  { id: 'fee-1001', studentId: 'SID-1001', amount: 3000, amountPaid: 3000, status: 'Paid', plan: 'Full Payment' },
  { id: 'fee-1002', studentId: 'SID-1002', amount: 2500, amountPaid: 2500, status: 'Paid', plan: 'Two Installments' },
  { id: 'fee-1003', studentId: 'SID-1003', amount: 3000, amountPaid: 1500, status: 'Pending', plan: 'Two Installments' },
  { id: 'fee-1004', studentId: 'SID-1004', amount: 2500, amountPaid: 0, status: 'Pending', plan: 'Monthly Plan' },
  { id: 'fee-1005', studentId: 'SID-1005', amount: 3000, amountPaid: 3000, status: 'Paid', plan: 'Full Payment' },
  { id: 'fee-1006', studentId: 'SID-1006', amount: 2500, amountPaid: 2000, status: 'Pending', plan: 'Monthly Plan' },
  { id: 'fee-1007', studentId: 'SID-1007', amount: 3000, amountPaid: 0, status: 'Overdue', plan: 'Full Payment' },
  { id: 'fee-1008', studentId: 'SID-1008', amount: 2500, amountPaid: 2500, status: 'Paid', plan: 'Full Payment' },
  { id: 'fee-1009', studentId: 'SID-1009', amount: 3000, amountPaid: 500, status: 'Pending', plan: 'Monthly Plan' },
  { id: 'fee-1010', studentId: 'SID-1010', amount: 2500, amountPaid: 1250, status: 'Pending', plan: 'Two Installments' },
];

export const USERS: User[] = [
    {
      id: 'user-1',
      username: 'Admin',
      email: 'admin@example.com',
      role: 'Admin',
      password: 'admin',
      avatarUrl: 'https://picsum.photos/seed/admin/100/100',
      imageHint: 'person avatar'
    },
    {
        id: 'user-2',
        username: 'Teacher',
        email: 'teacher@example.com',
        role: 'Teacher',
        password: 'teacher',
        avatarUrl: 'https://picsum.photos/seed/teacher/100/100',
        imageHint: 'person avatar'
    }
];

export const PERMISSIONS: {id: string, label: string}[] = [
    { id: '/dashboard/preschool', label: 'Preschool Dashboard' },
    { id: '/dashboard/student-management', label: 'Student Management' },
    { id: '/dashboard/attendance', label: 'Attendance' },
    { id: '/dashboard/grades', label: 'Grades' },
    { id: '/dashboard/financial', label: 'Financial' },
    { id: '/dashboard/forms', label: 'Forms' },
    { id: '/dashboard/reports', label: 'Reports' },
    { id: '/dashboard/graduation', label: 'Graduation' },
    { id: '/dashboard/after-care', label: 'After-Care' },
    { id: '/dashboard/manage-users', label: 'Manage Users'},
];

export const DEFAULT_TEACHER_PERMISSIONS: string[] = ['/dashboard/preschool', '/dashboard/attendance', '/dashboard/grades'];

    